### PR TITLE
Fixes #17 Update build command

### LINKED ISSUE #17: Build image does not work
there are many variables defined in the Dockerfile. the simple build command does not work at all.

```
# docker build -t postfix .
Sending build context to Docker daemon   362 kB
Error response from daemon: Syntax error - can't find = in "spec.expose". Must be of the form: name=value
```

(@TomasTomecek edited formatting)

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

This Pull Request updates the README.md file and brings new documentation
how to build a container with the other `DISTRO`.

### CODE REVIEW

**Comment by phracek** [comment]
@bnlcnd Please have a look on this pull request and let me know if it works for you.

**Comment by bnlcnd** [comment]
looks great. Thank you.

**Comment by TomasTomecek** [comment]
could we also rename dockerfile to dockerfile.template?

**Comment by phracek** [comment]
@bnlcnd @TomasTomecek Dockerfile is renamed to Dockerfile.template.

**Comment by TomasTomecek** [comment]
One more nit and I think we are good to merge. Could you please write down into readme that:
```
This container image utilizes [distgen](https://github.com/devexp-db/distgen) for Dockerfile templating. Please make sure that you have the tool installed before trying to build this image.
```

Thank you!

**Review by TomasTomecek — APPROVED** [review]
LGTM, nicely done

**Pull request merged**
